name: Init Api

on:
  workflow_dispatch:

env:
  CHUNK_SIZE: 20
  FIRST_CHUNK_SIZE: 40
  ALIAS: ART

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    matrix:
      include:
        - language_code: km
        - language_code: en
    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/kh-data
          path: src/databases/data
          token: ${{ secrets.GH_PAT }}

      - name: Checkout api
        uses: actions/checkout@v4
        with:
          repository: cltnp/kh
          path: apidata
          token: ${{ secrets.GH_PAT }}

      - name: Switch language ${{ matrix.language_code }}
        working-directory: apidata
        run: git switch -c ${{ matrix.language_code }}

      - name: Clean
        run: find apidata -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Init Api
        run: node src/api/init_api.js

      - name: Push
        working-directory: apidata
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m ':white_check_mark: Init Api'
          git push origin ${{ matrix.language_code }} -f
