name: Update Api

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-api

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/kh-data
          path: src/databases/data
          token: ${{ secrets.GH_PAT }}

      - name: Checkout api
        uses: actions/checkout@v4
        with:
          repository: cltnp/kh
          path: apidata
          token: ${{ secrets.GH_PAT }}

      - name: Update Api
        run: node src/api/update_api.js

      - name: Push
        working-directory: apidata
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m ':white_check_mark: Init Api'
          git push origin main -f
